name: titled_page_view
description: A Flutter PageView with an additional title bar and optional controls.
version: 0.1.1
author: Kevin Kleinbeck <KeKleinbeck@gmail.com>
homepage: https://github.com/KKleinbeck/titled_page_view

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
